// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl6FOpu2b-_asji7CTXxMjQxyr0KZ_BzY',
    appId: '1:170364194455:web:62497c29d43fb4969923d2',
    messagingSenderId: '170364194455',
    projectId: 'datingo-69e73',
    authDomain: 'datingo-69e73.firebaseapp.com',
    storageBucket: 'datingo-69e73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJG-vY5i88hI6clJ3Geh2jm8titCW6QoU',
    appId: '1:170364194455:android:ad5762e09c5ac4f09923d2',
    messagingSenderId: '170364194455',
    projectId: 'datingo-69e73',
    storageBucket: 'datingo-69e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmD2I4IvRyBEYjZG3UZTCEfJErMhm-X8Y',
    appId: '1:170364194455:ios:97b2c218fe25a1a09923d2',
    messagingSenderId: '170364194455',
    projectId: 'datingo-69e73',
    storageBucket: 'datingo-69e73.appspot.com',
    iosClientId: '170364194455-lr3c7fmb022apdbpsnsdrgat8p1bdeha.apps.googleusercontent.com',
    iosBundleId: 'com.khalafawy.datingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmD2I4IvRyBEYjZG3UZTCEfJErMhm-X8Y',
    appId: '1:170364194455:ios:97b2c218fe25a1a09923d2',
    messagingSenderId: '170364194455',
    projectId: 'datingo-69e73',
    storageBucket: 'datingo-69e73.appspot.com',
    iosClientId: '170364194455-lr3c7fmb022apdbpsnsdrgat8p1bdeha.apps.googleusercontent.com',
    iosBundleId: 'com.khalafawy.datingo',
  );
}
