// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBOf-vTtqUXYeS0B4Bq3YH1usnjxmc1Ko',
    appId: '1:1011468000144:web:9bdc39ac360c3c77c57115',
    messagingSenderId: '1011468000144',
    projectId: 'datingo-8aa3d',
    authDomain: 'datingo-8aa3d.firebaseapp.com',
    storageBucket: 'datingo-8aa3d.appspot.com',
    measurementId: 'G-MT360KWN5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5KwOzFjeQcaaZayRUB3X9tG00kuldi30',
    appId: '1:1011468000144:android:a6bf45cd7ee3aad4c57115',
    messagingSenderId: '1011468000144',
    projectId: 'datingo-8aa3d',
    storageBucket: 'datingo-8aa3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDauV9DOo6eK0_pSnO4CCeTOtw6X1Sy11k',
    appId: '1:1011468000144:ios:9c705ed62b023488c57115',
    messagingSenderId: '1011468000144',
    projectId: 'datingo-8aa3d',
    storageBucket: 'datingo-8aa3d.appspot.com',
    iosClientId: '1011468000144-6ac9fpevtbg88hggsjp1eouujuhbes7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.arrowDatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDauV9DOo6eK0_pSnO4CCeTOtw6X1Sy11k',
    appId: '1:1011468000144:ios:9c705ed62b023488c57115',
    messagingSenderId: '1011468000144',
    projectId: 'datingo-8aa3d',
    storageBucket: 'datingo-8aa3d.appspot.com',
    iosClientId: '1011468000144-6ac9fpevtbg88hggsjp1eouujuhbes7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.arrowDatingApp',
  );
}
